nav:
  Home: /
  About: /about/
  Writing: /archives/
  Resources: /resources/

projects_url: http://github.com/themikejr

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/mikepedia-120.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/themikejr
        twitter: http://twitter.com/themikejr
        linkedin: https://www.linkedin.com/in/michael-brinker-b5283b47/ 
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: 

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-11265464-2 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id: themikejr
        google_plus:
